name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-to-scratch-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Salesforce CLI with NPM
        run: |
          npm install sfdx-cli --global --force
          npm install @salesforce/cli --global --force

      - name: Write the dev hub token into a file
        run: 'echo ${{secrets.SFDX_AUTH_URL_DEVHUB}} > devHubAuthToken'

      - name: Authorize with the dev hub
        run: sfdx force:auth:sfdxurl:store -f devHubAuthToken --setalias DevHub --setdefaultdevhubusername

      - name: Create scratch org
        run: sfdx force:org:create --definitionfile config/project-scratch-def.json --setalias ScratchOrg --wait 30 --durationdays 1 --setdefaultusername

      - name: Push source
        run: sfdx force:source:push --targetusername ScratchOrg

      - name: Run tests
        run: sf apex run test --target-org ScratchOrg --code-coverage --result-format human --output-dir ./tests/apex --test-level RunLocalTests --wait 30

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: Apex

      - name: Delete scratch org
        if: always()
        run: sf org delete scratch --target-org ScratchOrg --no-prompt
